[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
tauri-example = { path = "tauri-example/src-tauri" }

[workspace]
members = [
    "tauri-example/src-tauri"
]
